import React from 'react'
import './Home.scss'

const Home = () => {
  return (
    <div className='home_container'>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
      <h3>abc</h3>
    </div>
  )
}

export default Home